tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f5f3f3",
        "on-primary-container": "#fffbff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fbf9f8",
        "on-secondary-fixed-variant": "#474646",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#f7fff2",
        "on-secondary-container": "#656464",
        outline: "#907065",
        "surface-container-high": "#e9e8e7",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed-variant": "#00531e",
        "surface-variant": "#e4e2e2",
        tertiary: "#006b29",
        "surface-dim": "#dbdad9",
        "secondary-fixed-dim": "#c8c6c5",
        "on-secondary": "#ffffff",
        error: "#ba1a1a",
        surface: "#fbf9f8",
        "primary-fixed": "#ffdbd0",
        "primary-container": "#d24200",
        primary: "#a83300",
        "error-container": "#ffdad6",
        "on-surface-variant": "#5c4037",
        secondary: "#5f5e5e",
        "tertiary-container": "#008735",
        "inverse-surface": "#303031",
        "on-background": "#1b1c1c",
        "on-secondary-fixed": "#1c1b1b",
        background: "#fbf9f8",
        "tertiary-fixed": "#69ff87",
        "outline-variant": "#e5beb2",
        "inverse-on-surface": "#f2f0f0",
        "tertiary-fixed-dim": "#3ce36a",
        "surface-tint": "#ac3500",
        "secondary-container": "#e5e2e1",
        "surface-container": "#efeded",
        "primary-fixed-dim": "#ffb59d",
        "on-surface": "#1b1c1c",
        "surface-container-highest": "#e4e2e2",
        "on-primary-fixed-variant": "#832600",
        "inverse-primary": "#ffb59d",
        "on-primary-fixed": "#390c00",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#002108",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "container-max-width": "1280px",
        "margin-desktop": "40px",
        gutter: "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "display-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
      },
    },
  },
};
