<?php
$pageTitle = 'Zesto — Delicious Food Delivered Fast';
$pageDesc = 'Browse delicious food items from top restaurants near you. Fast delivery at your doorstep.';
include 'header.php';
?>

<!-- ===== HERO ===== -->
<section class="relative min-h-[80vh] flex flex-col justify-center px-6 md:px-12 lg:px-16 py-12 bg-[#fdfbf9]">
  <div class="max-w-7xl mx-auto w-full">
    <div class="lg:grid lg:grid-cols-12 lg:items-center gap-12">
      <div class="lg:col-span-7 animate-fade-in-up">
        <span class="text-[10px] uppercase tracking-[0.22em] font-extrabold text-primary block mb-4">Curated dishes from your favorite kitchens.</span>
        <h1 class="animated-heading text-5xl md:text-6xl lg:text-7xl font-extrabold font-title mb-6 leading-[1.05]" style="letter-spacing:-0.03em" data-text="Fresh meals,&#10;delivered with care." data-char-delay="35" data-initial-delay="100" data-duration="500"></h1>
        <p class="fade-in opacity-0 text-zinc-650 text-base md:text-lg mb-8 max-w-lg leading-relaxed" data-delay="700" data-duration="1000">
          Experience our new seasonal menus, where timeless culinary heritage meets contemporary local flavors. Prepared by master artisans.
        </p>
        <div class="fade-in opacity-0 flex flex-wrap gap-4" data-delay="1000" data-duration="1000">
          <a href="#menu" class="bg-primary text-white hover:bg-primary-container px-8 py-3 rounded text-xs uppercase tracking-wider font-semibold transition-all shadow-sm active:scale-95 flex items-center">
            Order Now
          </a>
        </div>
      </div>
      
      <div class="lg:col-span-5 fade-in opacity-0 mt-12 lg:mt-0" data-delay="1200" data-duration="1000">
        <div class="relative rounded overflow-hidden shadow-sm border border-zinc-200/60" style="height: 440px;">
          <img src="https://images.unsplash.com/photo-1504674900247-0877df9cc836?q=80&w=600&auto=format&fit=crop" 
               alt="Gourmet Table" 
               class="w-full h-full object-cover" />
          <div class="absolute inset-0 bg-gradient-to-t from-black/35 to-transparent"></div>
          <div class="absolute bottom-6 left-6 text-white">
            <p class="text-[9px] uppercase tracking-widest font-bold opacity-85">Featured Selection</p>
            <h4 class="font-title text-xl font-bold mt-1">Culinary Tastings</h4>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<div id="menu" class="bg-transparent text-zinc-800 relative">

<!-- ===== CATEGORY FILTER BAR ===== -->
<div class="sticky top-0 z-40 zesto-glass border-b border-zinc-200/40">
  <div class="max-w-7xl mx-auto px-6 md:px-12 lg:px-16">
    <div id="category-bar" class="flex gap-4 overflow-x-auto hide-scrollbar py-4 justify-start">
      <!-- generated by JS -->
    </div>
  </div>
</div>

<!-- ===== FILTER / SORT BAR ===== -->
<div class="max-w-7xl mx-auto px-6 md:px-12 lg:px-16 py-8 flex items-center justify-between gap-6 flex-wrap">
  <div class="flex items-center gap-4 flex-wrap">
    <span class="text-xs text-zinc-500 font-semibold uppercase tracking-wider" id="results-count">Loading…</span>
    <div class="flex items-center bg-white rounded border border-zinc-200 px-4 py-2 gap-2 focus-within:border-primary transition-all">
      <span class="material-symbols-outlined text-zinc-400" style="font-size:18px">search</span>
      <input id="menu-search" type="text" placeholder="Search dishes, restaurants..."
        class="bg-transparent border-none outline-none text-xs w-48 font-medium text-zinc-800 placeholder:text-zinc-400 focus:ring-0 focus:outline-none p-0"
        oninput="filterItems()"/>
    </div>
    <div class="flex gap-2">
      <button onclick="setDietFilter('all')" id="diet-all"
        class="diet-btn active px-4 py-1.5 rounded text-xs uppercase tracking-wider font-semibold border border-zinc-200 transition-all bg-primary text-white">All</button>
      <button onclick="setDietFilter('veg')" id="diet-veg"
        class="diet-btn px-4 py-1.5 rounded text-xs uppercase tracking-wider font-semibold border border-zinc-200 transition-all text-zinc-700 hover:bg-black/5 bg-white">Veg</button>
      <button onclick="setDietFilter('nonveg')" id="diet-nonveg"
        class="diet-btn px-4 py-1.5 rounded text-xs uppercase tracking-wider font-semibold border border-zinc-200 transition-all text-zinc-700 hover:bg-black/5 bg-white">Non-Veg</button>
    </div>
  </div>
  <div class="flex items-center gap-2">
    <label class="text-xs font-bold uppercase tracking-wider text-zinc-500">Sort:</label>
    <select onchange="setSortOrder(this.value)"
      class="text-xs font-semibold text-zinc-800 border border-zinc-200 rounded px-4 py-2 bg-white outline-none cursor-pointer focus:border-primary">
      <option value="popular">Popular</option>
      <option value="price-asc">Price ↑</option>
      <option value="price-desc">Price ↓</option>
      <option value="rating">Top Rated</option>
    </select>
  </div>
</div>

<!-- ===== FOOD GRID ===== -->
<main class="max-w-7xl mx-auto px-6 md:px-12 lg:px-16 pb-28">
  <div id="food-grid" class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
    <!-- Food cards rendered by JS -->
  </div>
  <div id="empty-state" class="hidden flex-col items-center justify-center py-24 gap-2 text-center">
    <h3 class="font-title text-2xl font-extrabold text-zinc-800">No items found</h3>
    <p class="text-zinc-500 text-sm max-w-xs">Try searching a different keyword or resetting your category filter.</p>
    <button onclick="resetFilters()" class="btn-outline mt-4">Show all items</button>
  </div>
</main>

<!-- ===== WHY ZESTO (LUXE-STYLE) ===== -->
<section class="max-w-7xl mx-auto px-6 md:px-12 lg:px-16 py-20 border-t border-zinc-200/50 bg-[#fdfbf9]">
  <div class="grid grid-cols-1 lg:grid-cols-12 gap-12 items-center">
    <!-- Left column: elegant photograph -->
    <div class="lg:col-span-5 relative rounded overflow-hidden shadow-sm border border-zinc-200/60" style="height: 480px;">
      <img src="https://images.unsplash.com/photo-1546069901-ba9599a7e63c?q=80&w=600&auto=format&fit=crop" 
           alt="Sourced Fresh" 
           class="w-full h-full object-cover" />
    </div>

    <!-- Right column: text details -->
    <div class="lg:col-span-7 flex flex-col gap-6">
      <div>
        <span class="text-[10px] uppercase tracking-[0.2em] font-extrabold text-primary block mb-3">Our Philosophy</span>
        <h2 class="font-title text-4xl font-extrabold text-zinc-900 leading-tight">Built for Freshness,<br/>Mindful of the Future</h2>
        <p class="text-zinc-600 text-sm mt-4 leading-relaxed max-w-lg">
          We believe that culinary luxury should not come at the cost of the planet. Our commitment to sustainable sourcing, local partnerships, and zero plastic is woven into every dish we prepare.
        </p>
      </div>

      <!-- 2x2 grid of elegant boxes -->
      <div class="grid grid-cols-1 sm:grid-cols-2 gap-6 mt-4">
        <div class="p-5 border border-zinc-200/60 rounded bg-white">
          <span class="material-symbols-outlined text-primary mb-3" style="font-size:22px">eco</span>
          <h4 class="font-title text-base font-bold text-zinc-900">Sustainability</h4>
          <p class="text-zinc-500 text-xs mt-1.5 leading-relaxed">Eco-conscious sourcing and 100% biodegradable packaging to protect our planet.</p>
        </div>
        <div class="p-5 border border-zinc-200/60 rounded bg-white">
          <span class="material-symbols-outlined text-primary mb-3" style="font-size:22px">workspace_premium</span>
          <h4 class="font-title text-base font-bold text-zinc-900">Quality</h4>
          <p class="text-zinc-500 text-xs mt-1.5 leading-relaxed">Every ingredient is handpicked from organic local farms to ensure unrivaled freshness.</p>
        </div>
        <div class="p-5 border border-zinc-200/60 rounded bg-white">
          <span class="material-symbols-outlined text-primary mb-3" style="font-size:22px">restaurant</span>
          <h4 class="font-title text-base font-bold text-zinc-900">Craftsmanship</h4>
          <p class="text-zinc-500 text-xs mt-1.5 leading-relaxed">Our master chefs combine classic traditions with modern culinary techniques.</p>
        </div>
        <div class="p-5 border border-zinc-200/60 rounded bg-white">
          <span class="material-symbols-outlined text-primary mb-3" style="font-size:22px">visibility</span>
          <h4 class="font-title text-base font-bold text-zinc-900">Transparency</h4>
          <p class="text-zinc-500 text-xs mt-1.5 leading-relaxed">Full traceability of our ingredients from local farms straight to your table.</p>
        </div>
      </div>
    </div>
  </div>
</section>

<!-- ===== FLOATING CART (mobile) ===== -->
<div id="floating-cart" class="fixed bottom-6 left-1/2 -translate-x-1/2 z-50 hidden">
  <a href="cart.php" class="flex items-center gap-4 bg-[#221f1d] text-white rounded-xl px-6 py-3.5 shadow-lg font-bold text-xs uppercase tracking-wider animate-scale-in">
    <span class="material-symbols-outlined text-white" style="font-size:18px">shopping_cart</span>
    <span id="float-cart-info">View Cart</span>
    <span class="bg-[#8a4f35] text-white rounded px-2 py-0.5 text-[10px]" id="float-cart-price">₹0</span>
    <span class="material-symbols-outlined text-white" style="font-size:16px">arrow_forward</span>
  </a>
</div>

</div>

<div id="toast-container"></div>
<script src="js/cart.js"></script>
<script>
function initFadeInComponents() {
  document.querySelectorAll('.fade-in').forEach((el) => {
    const delay = Number(el.dataset.delay || 0);
    const duration = Number(el.dataset.duration || 1000);
    el.style.transitionDuration = `${duration}ms`;
    setTimeout(() => {
      el.classList.remove('opacity-0');
      el.classList.add('opacity-100');
    }, delay);
  });
}

function initAnimatedHeading() {
  document.querySelectorAll('.animated-heading').forEach((heading) => {
    const text = heading.dataset.text || '';
    const charDelay = Number(heading.dataset.charDelay || 30);
    const initialDelay = Number(heading.dataset.initialDelay || 200);
    const duration = Number(heading.dataset.duration || 500);
    const lines = text.split('\n');
    heading.innerHTML = lines.map((line, lineIndex) => {
      const lineLength = line.length;
      const chars = [...line].map((char, charIndex) => {
        const delay = (lineIndex * lineLength * charDelay) + (charIndex * charDelay) + initialDelay;
        const output = char === ' ' ? '&nbsp;' : char;
        return `<span class="inline-block opacity-0 translate-x-[-18px] transition-all ease-out" style="transition-delay:${delay}ms;transition-duration:${duration}ms">${output}</span>`;
      }).join('');
      return `<span class="block">${chars}</span>`;
    }).join('');

    requestAnimationFrame(() => {
      heading.querySelectorAll('span span').forEach((span) => {
        span.classList.remove('opacity-0', 'translate-x-[-18px]');
        span.classList.add('opacity-100', 'translate-x-0');
      });
    });
  });
}

/* ===================================================
   Categories
=================================================== */
const CATEGORIES = [
  { id:'all',          label:'All',            emoji:'' },
  { id:'bread',        label:'Breads',         emoji:'' },
  { id:'rice',         label:'Rice Dishes',    emoji:'' },
  { id:'eggs',         label:'Eggs',           emoji:'' },
  { id:'indian',       label:'Indian',         emoji:'' },
  { id:'international',label:'International',  emoji:'' },
];

/* ===================================================
   Food Data — 21 items from reference image
   Each with a unique, verified Wikipedia image
=================================================== */
const FOODS = [

  /* ── BREADS ──────────────────────────────────────── */
  {
    id:'f01', name:"Baker's Basket Bread",
    restaurant:"Baker's Basket",
    cat:'bread', price:49, rating:4.2, ratingCount:3.1,
    veg:true, time:'5-10',
    image:'https://images.unsplash.com/photo-1509440159596-0249088772ff?w=400&q=80',
    badge:''
  },
  {
    id:'f02', name:'Roti',
    restaurant:'Dhaba Junction',
    cat:'bread', price:15, rating:4.5, ratingCount:8.3,
    veg:true, time:'5-10',
    image:'https://images.unsplash.com/photo-1565557623262-b51c2513a641?w=400&q=80',
    badge:'Daily Staple'
  },
  {
    id:'f03', name:'Paratha',
    restaurant:'Dhaba Junction',
    cat:'bread', price:45, rating:4.7, ratingCount:6.2,
    veg:true, time:'10-15',
    image:'https://images.unsplash.com/photo-1601050690597-df0568f70950?w=400&q=80',
    badge:'Morning Special'
  },

  /* ── RICE DISHES ─────────────────────────────────── */
  {
    id:'f04', name:'Steamed Rice',
    restaurant:'Spice Garden',
    cat:'rice', price:59, rating:4.1, ratingCount:4.8,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?w=400&q=80',
    badge:''
  },
  {
    id:'f05', name:'Pulao',
    restaurant:'Spice Garden',
    cat:'rice', price:119, rating:4.5, ratingCount:3.4,
    veg:true, time:'20-25',
    image:'https://images.unsplash.com/photo-1630851840633-f96999247032?w=400&q=80',
    badge:'Veg Special'
  },
  {
    id:'f06', name:'Biryani',
    restaurant:'Biryani House',
    cat:'rice', price:249, rating:4.8, ratingCount:9.2,
    veg:false, time:'30-40',
    image:'https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=400&q=80',
    badge:'Bestseller'
  },
  {
    id:'f07', name:'Fried Rice',
    restaurant:'Wok & Roll',
    cat:'rice', price:149, rating:4.5, ratingCount:4.7,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1512058564366-18510be2db19?w=400&q=80',
    badge:'Indo-Chinese'
  },

  /* ── EGGS ────────────────────────────────────────── */
  {
    id:'f08', name:'Boiled Eggs Set',
    restaurant:'Egg Station',
    cat:'eggs', price:29, rating:4.2, ratingCount:2.8,
    veg:false, time:'10-15',
    image:'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&q=80',
    badge:'Protein Rich'
  },
  {
    id:'f09', name:'Omelette',
    restaurant:'Egg Station',
    cat:'eggs', price:59, rating:4.5, ratingCount:3.6,
    veg:false, time:'10-15',
    image:'https://images.unsplash.com/photo-1525351484163-7529414344d8?w=400&q=80',
    badge:'Fresh Made'
  },
  {
    id:'f10', name:'Scrambled Eggs',
    restaurant:'Egg Station',
    cat:'eggs', price:69, rating:4.4, ratingCount:2.2,
    veg:false, time:'10-15',
    image:'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=400&q=80',
    badge:'Breakfast'
  },

  /* ── INDIAN ──────────────────────────────────────── */
  {
    id:'f11', name:'Idli',
    restaurant:'Saravana Bhavan',
    cat:'indian', price:69, rating:4.6, ratingCount:5.3,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=400&q=80',
    badge:'South Indian'
  },
  {
    id:'f12', name:'Dosa',
    restaurant:'Saravana Bhavan',
    cat:'indian', price:89, rating:4.7, ratingCount:7.1,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1668236543090-82eba5ee5976?w=400&q=80',
    badge:'Crispy'
  },
  {
    id:'f13', name:'Paneer Curry',
    restaurant:'Shahi Rasoi',
    cat:'indian', price:199, rating:4.6, ratingCount:4.4,
    veg:true, time:'20-30',
    image:'https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=400&q=80',
    badge:'Veg Favourite'
  },
  {
    id:'f14', name:'Chicken Curry',
    restaurant:'Punjab Grill',
    cat:'indian', price:249, rating:4.8, ratingCount:7.9,
    veg:false, time:'25-35',
    image:'https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=400&q=80',
    badge:'Must Try'
  },
  {
    id:'f15', name:'Mutton Korma',
    restaurant:"Nawab's Kitchen",
    cat:'indian', price:329, rating:4.8, ratingCount:3.6,
    veg:false, time:'35-45',
    image:'https://images.unsplash.com/photo-1574653853027-5382a3d23a15?w=400&q=80',
    badge:'Rich & Creamy'
  },

  /* ── INTERNATIONAL ───────────────────────────────── */
  {
    id:'f16', name:'Indo-Chinese Noodles',
    restaurant:'Wok & Roll',
    cat:'international', price:129, rating:4.4, ratingCount:5.8,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1569050467447-ce54b3bbc37d?w=400&q=80',
    badge:'Indo-Chinese'
  },
  {
    id:'f17', name:'Pasta Arrabiata',
    restaurant:'Pasta Fresca',
    cat:'international', price:189, rating:4.6, ratingCount:4.2,
    veg:true, time:'20-25',
    image:'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=400&q=80',
    badge:''
  },
  {
    id:'f18', name:'Margherita Classic Pizza',
    restaurant:'Pizza Primo',
    cat:'international', price:249, rating:4.7, ratingCount:6.3,
    veg:true, time:'20-30',
    image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&q=80',
    badge:'Cheesy'
  },
  {
    id:'f19', name:'Mashed Potatoes',
    restaurant:'Green Plates',
    cat:'international', price:89, rating:4.3, ratingCount:1.9,
    veg:true, time:'15-20',
    image:'https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=400&q=80',
    badge:'Comfort Food'
  },
  {
    id:'f20', name:'Grilled Chicken',
    restaurant:'Frontier Grill',
    cat:'international', price:279, rating:4.7, ratingCount:5.5,
    veg:false, time:'25-35',
    image:'https://images.unsplash.com/photo-1598103442097-8b74394b95c3?w=400&q=80',
    badge:'Grilled Fresh'
  },
  {
    id:'f21', name:'Roasted Vegetables',
    restaurant:'Green Plates',
    cat:'international', price:149, rating:4.4, ratingCount:2.1,
    veg:true, time:'20-25',
    image:'https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=400&q=80',
    badge:'Healthy'
  },
];

/* ===================================================
   State & Auth Configuration
=================================================== */
const IS_LOGGED_IN = <?php echo isset($_SESSION['user_id']) ? 'true' : 'false'; ?>;

let activeCategory = 'all';
let activeDiet     = 'all';
let activeSort     = 'popular';
let searchQuery    = '';

/* ===================================================
   Init
=================================================== */
document.addEventListener('DOMContentLoaded', () => {
  initAnimatedHeading();
  initFadeInComponents();
  buildCategoryBar();
  renderFoods();
  loadLocation();
  updateFloatingCart();
  updateCartBadge();

  // Sync mobile search with desktop
  const mobile = document.getElementById('menu-search-mobile');
  if (mobile) mobile.addEventListener('input', () => {
    searchQuery = mobile.value;
    const desk = document.getElementById('menu-search');
    if (desk) desk.value = mobile.value;
    renderFoods();
  });

  // Recovery of pending actions
  if (IS_LOGGED_IN) {
    const pending = localStorage.getItem('zyrop_pending_action');
    if (pending) {
      try {
        const action = JSON.parse(pending);
        localStorage.removeItem('zyrop_pending_action');
        if (action && action.type === 'add_to_cart') {
          addToCart(action.id);
        } else if (action && action.type === 'change_qty') {
          changeQty(action.id, action.delta);
        }
      } catch (e) {
        localStorage.removeItem('zyrop_pending_action');
      }
    }
  }
});

window.addEventListener('zyrop:cart-updated', () => {
  updateFloatingCart();
  updateCartBadge();
});

/* ===================================================
   Category Bar
=================================================== */
function buildCategoryBar() {
  const bar = document.getElementById('category-bar');
  bar.innerHTML = CATEGORIES.map(c => `
    <button id="cat-${c.id}" onclick="setCategory('${c.id}')"
      class="flex-shrink-0 flex items-center px-5 py-2 rounded text-xs uppercase tracking-wider font-semibold border transition-all duration-200
             ${c.id==='all' ? 'bg-primary text-white border-primary font-bold' : 'border-outline-variant text-secondary hover:bg-black/5'}">
      ${c.label}
    </button>
  `).join('');
}

function setCategory(id) {
  activeCategory = id;
  document.querySelectorAll('[id^="cat-"]').forEach(btn => {
    btn.className = 'flex-shrink-0 flex items-center px-5 py-2 rounded text-xs uppercase tracking-wider font-semibold border transition-all duration-200 border-outline-variant text-secondary hover:bg-black/5';
  });
  const active = document.getElementById(`cat-${id}`);
  if (active) active.className = 'flex-shrink-0 flex items-center px-5 py-2 rounded text-xs uppercase tracking-wider font-bold border transition-all duration-200 bg-primary text-white border-primary';
  renderFoods();
}

/* ===================================================
   Filters & Sort
=================================================== */
function setDietFilter(diet) {
  activeDiet = diet;
  document.querySelectorAll('.diet-btn').forEach(b => {
    b.className = 'diet-btn px-4 py-1.5 rounded text-xs uppercase tracking-wider font-semibold border border-zinc-200 transition-all text-zinc-700 hover:bg-black/5 bg-white';
  });
  const el = document.getElementById(`diet-${diet}`);
  if (el) el.className = 'diet-btn active px-4 py-1.5 rounded text-xs uppercase tracking-wider font-bold border border-zinc-200 transition-all bg-primary text-white';
  renderFoods();
}

function setSortOrder(val) {
  activeSort = val;
  renderFoods();
}

function filterItems() {
  const desk   = document.getElementById('menu-search');
  const mobile = document.getElementById('menu-search-mobile');
  searchQuery  = (desk && document.activeElement === desk) ? desk.value : (mobile ? mobile.value : '');
  renderFoods();
}

function resetFilters() {
  activeCategory = 'all';
  activeDiet     = 'all';
  searchQuery    = '';
  const desk   = document.getElementById('menu-search');
  const mobile = document.getElementById('menu-search-mobile');
  if (desk)   desk.value   = '';
  if (mobile) mobile.value = '';
  buildCategoryBar();
  setDietFilter('all');
  renderFoods();
}

/* ===================================================
   Render Foods
=================================================== */
function renderFoods() {
  let items = [...FOODS];

  if (activeCategory !== 'all') items = items.filter(f => f.cat === activeCategory);
  if (activeDiet === 'veg')     items = items.filter(f => f.veg);
  if (activeDiet === 'nonveg')  items = items.filter(f => !f.veg);

  const q = searchQuery.trim().toLowerCase();
  if (q) {
    items = items.filter(f =>
      f.name.toLowerCase().includes(q) ||
      f.restaurant.toLowerCase().includes(q)
    );
  }

  if (activeSort === 'price-asc')  items.sort((a,b) => a.price - b.price);
  if (activeSort === 'price-desc') items.sort((a,b) => b.price - a.price);
  if (activeSort === 'rating')     items.sort((a,b) => b.rating - a.rating);

  const count = document.getElementById('results-count');
  if (count) count.textContent = `${items.length} item${items.length !== 1 ? 's' : ''} found`;

  const grid  = document.getElementById('food-grid');
  const empty = document.getElementById('empty-state');

  if (items.length === 0) {
    grid.classList.add('hidden');
    empty.classList.remove('hidden');
    empty.classList.add('flex');
    return;
  }
  empty.classList.add('hidden');
  empty.classList.remove('flex');
  grid.classList.remove('hidden');
  grid.innerHTML = items.map((f, i) => foodCard(f, i)).join('');
}

/* ===================================================
   Food Card HTML
=================================================== */
function foodCard(f, i) {
  const qty = ZyropCart.getItemQty(f.id);
  const rc  = f.ratingCount;
  const ratingStr = (typeof rc === 'number' && rc >= 1) ? `${rc}k` : `${rc}`;
  
  // Fallback image
  const imageUrl = f.image ? `${f.image}${f.image.includes('?') ? '&' : '?'}v=2` : 'https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=400&q=80';
  
  const dietLabel = f.veg ? 'Veg' : 'Non-Veg';
  const dietClass = f.veg ? 'text-emerald-700 bg-emerald-50 border-emerald-100' : 'text-amber-800 bg-amber-50 border-amber-100';

  return `
  <div class="food-card animate-fade-in-up" style="animation-delay:${i * 0.05}s">
    <div class="relative overflow-hidden" style="height:200px">
      <img src="${imageUrl}" alt="${f.name}" class="w-full h-full object-cover transition-transform duration-500 hover:scale-105" loading="lazy"/>
      ${f.badge ? `<span class="absolute top-3 left-3 bg-[#221f1d] text-white text-[9px] uppercase tracking-wider font-bold px-2.5 py-1 rounded">${f.badge}</span>` : ''}
      <span class="absolute top-3 right-3 text-[9px] uppercase tracking-wider font-bold px-2 py-0.5 rounded border ${dietClass}">${dietLabel}</span>
    </div>
    <div class="p-5 flex flex-col gap-3">
      <div>
        <p class="text-[9px] uppercase tracking-widest text-secondary font-semibold">${f.restaurant}</p>
        <h3 class="font-title text-lg font-bold text-on-surface leading-snug mt-1">${f.name}</h3>
      </div>
      <div class="flex items-center gap-3 text-xs text-secondary font-medium">
        <span class="flex items-center gap-1">
          <span class="text-zinc-400">★</span> ${f.rating} <span class="text-[10px] text-zinc-400">(${ratingStr} ratings)</span>
        </span>
        <span>·</span>
        <span>${f.time} min</span>
      </div>
      <div class="flex items-center justify-between mt-2 pt-2 border-t border-black/[0.03]">
        <span class="font-extrabold text-base text-on-surface">&#8377;${f.price}</span>
        ${qty === 0
          ? `<button onclick="addToCart('${f.id}')" id="add-btn-${f.id}"
               class="px-4 py-1.5 text-xs font-bold border border-zinc-200 rounded-md hover:border-[#8a4f35] hover:text-[#8a4f35] transition-all duration-200">
               Add to Cart
             </button>`
          : `<div class="qty-stepper" id="stepper-${f.id}">
               <button class="qty-btn" onclick="changeQty('${f.id}',-1)">−</button>
               <span class="qty-count" id="qty-${f.id}">${qty}</span>
               <button class="qty-btn" onclick="changeQty('${f.id}',1)">+</button>
             </div>`
        }
      </div>
    </div>
  </div>`;
}

/* ===================================================
   Cart Actions
=================================================== */
function addToCart(id) {
  const food = FOODS.find(f => f.id === id);
  if (!food) return;
  const qty = ZyropCart.addItem({ id:food.id, name:food.name, price:food.price, image:food.image, restaurant:food.restaurant, veg:food.veg });
  showToast(`${food.name} added to your cart.`, 'success', 2000);
  updateFoodCardBtn(id, qty);
  updateFloatingCart();
}

function changeQty(id, delta) {
  if (delta > 0) ZyropCart.incrementItem(id);
  else           ZyropCart.decrementItem(id);
  const qty = ZyropCart.getItemQty(id);
  updateFoodCardBtn(id, qty);
  updateFloatingCart();
}

function updateFoodCardBtn(id, qty) {
  const addBtn  = document.getElementById(`add-btn-${id}`);
  const stepper = document.getElementById(`stepper-${id}`);

  if (qty === 0) {
    if (stepper) {
      stepper.outerHTML = `<button onclick="addToCart('${id}')" id="add-btn-${id}"
        class="px-4 py-1.5 text-xs font-bold border border-zinc-200 rounded-md hover:border-[#8a4f35] hover:text-[#8a4f35] transition-all duration-200">
        Add to Cart
      </button>`;
    }
  } else {
    if (addBtn) {
      addBtn.outerHTML = `<div class="qty-stepper" id="stepper-${id}">
        <button class="qty-btn" onclick="changeQty('${id}',-1)">−</button>
        <span class="qty-count" id="qty-${id}">${qty}</span>
        <button class="qty-btn" onclick="changeQty('${id}',1)">+</button>
      </div>`;
    } else if (document.getElementById(`qty-${id}`)) {
      document.getElementById(`qty-${id}`).textContent = qty;
    }
  }
}

/* ===================================================
   Floating Cart
=================================================== */
function updateFloatingCart() {
  const count    = ZyropCart.getTotalCount();
  const subtotal = ZyropCart.getSubtotal();
  const fc       = document.getElementById('floating-cart');
  if (count > 0) {
    fc.classList.remove('hidden');
    document.getElementById('float-cart-info').textContent  = `${count} item${count > 1 ? 's' : ''}`;
    document.getElementById('float-cart-price').textContent = `\u20B9${subtotal}`;
  } else {
    fc.classList.add('hidden');
  }
}

/* ===================================================
   Cart Badge
=================================================== */
function updateCartBadge() {
  const count   = ZyropCart.getTotalCount();
  const badges  = document.querySelectorAll('.cart-count-badge');
  badges.forEach(b => {
    if (count > 0) {
      b.style.display = 'flex';
      b.textContent   = count;
    } else {
      b.style.display = 'none';
    }
  });
}

/* ===================================================
   Location
=================================================== */
function loadLocation() {
  const loc = JSON.parse(localStorage.getItem('zyrop_delivery_address') || 'null');
  const wrap = document.getElementById('header-location');
  const text = document.getElementById('header-loc-text');
  if (wrap) wrap.classList.remove('hidden');
  if (text) text.textContent = loc && loc.label ? loc.label.split(',')[0] : 'Set location';
}

function changeHeaderLocation() {
  window.location.href = 'cart.php';
}
</script>
<?php include 'footer.php'; ?>


